export const statusMeta = {
  compliant: {
    label: 'Compliant',
    className: 'bg-success/10 text-success border-success/20',
    dot: 'bg-success',
  },
  review: {
    label: 'Needs Review',
    className: 'bg-warning/10 text-warning border-warning/20',
    dot: 'bg-warning',
  },
  flagged: {
    label: 'Flagged',
    className: 'bg-destructive/10 text-destructive border-destructive/20',
    dot: 'bg-destructive',
  },
  processing: {
    label: 'Processing',
    className: 'bg-muted text-muted-foreground border-border',
    dot: 'bg-muted-foreground animate-pulse',
  },
}

export const recentDocuments = [
  {
    id: 'DOC-4821',
    name: 'Q4_2025_Annual_Report.pdf',
    category: 'Financial Statement',
    size: '4.2 MB',
    uploadedBy: 'A. Whitmore',
    uploadedAt: 'Jul 8, 2026 · 09:41',
    status: 'compliant',
    progress: 100,
  },
  {
    id: 'DOC-4820',
    name: 'AML_KYC_Verification_Batch12.pdf',
    category: 'Anti-Money Laundering',
    size: '1.8 MB',
    uploadedBy: 'R. Okafor',
    uploadedAt: 'Jul 8, 2026 · 08:57',
    status: 'review',
    progress: 100,
  },
  {
    id: 'DOC-4819',
    name: 'Vendor_Contract_Meridian_LLC.pdf',
    category: 'Contract',
    size: '922 KB',
    uploadedBy: 'S. Nakamura',
    uploadedAt: 'Jul 7, 2026 · 17:22',
    status: 'flagged',
    progress: 100,
  },
  {
    id: 'DOC-4818',
    name: 'SOX_Controls_Attestation.pdf',
    category: 'Regulatory Filing',
    size: '3.1 MB',
    uploadedBy: 'A. Whitmore',
    uploadedAt: 'Jul 7, 2026 · 14:05',
    status: 'compliant',
    progress: 100,
  },
  {
    id: 'DOC-4817',
    name: 'Wire_Transfer_Audit_June.pdf',
    category: 'Audit',
    size: '2.6 MB',
    uploadedBy: 'R. Okafor',
    uploadedAt: 'Jul 7, 2026 · 11:38',
    status: 'processing',
    progress: 64,
  },
  {
    id: 'DOC-4816',
    name: 'GDPR_Data_Processing_Addendum.pdf',
    category: 'Privacy',
    size: '740 KB',
    uploadedBy: 'S. Nakamura',
    uploadedAt: 'Jul 6, 2026 · 16:50',
    status: 'compliant',
    progress: 100,
  },
  {
    id: 'DOC-4815',
    name: 'Basel_III_Capital_Adequacy.pdf',
    category: 'Regulatory Filing',
    size: '5.4 MB',
    uploadedBy: 'A. Whitmore',
    uploadedAt: 'Jul 6, 2026 · 10:12',
    status: 'review',
    progress: 100,
  },
]
